# Generated by Django 5.1.2 on 2025-02-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependency',
            name='package_manager',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='overall_cvss_severity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
